/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Usuário
 */
public class AdicionarPet extends javax.swing.JFrame {

    /**
     * Creates new form AdicionarPet
     */
    public AdicionarPet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_nome2 = new javax.swing.JLabel();
        lb_especie = new javax.swing.JLabel();
        lb_idade = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        AdicionarPet = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_nome2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lb_nome2.setForeground(new java.awt.Color(1, 141, 185));
        lb_nome2.setText("Nome:");
        getContentPane().add(lb_nome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        lb_especie.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lb_especie.setForeground(new java.awt.Color(1, 141, 185));
        lb_especie.setText("Raça:");
        getContentPane().add(lb_especie, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        lb_idade.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lb_idade.setForeground(new java.awt.Color(1, 141, 185));
        lb_idade.setText("Idade:");
        getContentPane().add(lb_idade, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, -1, -1));

        jTextField10.setBackground(new java.awt.Color(255, 255, 255));
        jTextField10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(1, 141, 185), 2, true));
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 320, 40));

        jTextField9.setBackground(new java.awt.Color(255, 255, 255));
        jTextField9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(1, 141, 185), 2, true));
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 160, 40));

        jTextField8.setBackground(new java.awt.Color(255, 255, 255));
        jTextField8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(1, 141, 185), 2, true));
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 80, 40));

        jButton1.setContentAreaFilled(false);
        jButton1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jButton1CaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 120, 40));

        jButton2.setContentAreaFilled(false);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 120, 40));

        AdicionarPet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/AdicionarPet.png"))); // NOI18N
        getContentPane().add(AdicionarPet, new org.netbeans.lib.awtextra.AbsoluteConstraints(-11, 0, 750, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jButton1CaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jButton1CaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1CaretPositionChanged

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         // Ação após clicar no Botão Voltar
        SubMenuCadastro novoFrame = new SubMenuCadastro();
        novoFrame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionarPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionarPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionarPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionarPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdicionarPet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdicionarPet;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lb_especie;
    private javax.swing.JLabel lb_idade;
    private javax.swing.JLabel lb_nome2;
    // End of variables declaration//GEN-END:variables
}
