/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.PetController;
import javax.swing.JTextField;

/**
 *
 * @author Usuário
 */
public class AdicionarPet extends javax.swing.JFrame {
    
    private final PetController controller;
    /**
     * Creates new form AdicionarPet
     */
    public AdicionarPet() {
        initComponents();
        this.controller = new PetController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_nome2 = new javax.swing.JLabel();
        lb_especie = new javax.swing.JLabel();
        lb_idade = new javax.swing.JLabel();
        tf_nome = new javax.swing.JTextField();
        tf_raca = new javax.swing.JTextField();
        tf_idade = new javax.swing.JTextField();
        btn_voltar = new javax.swing.JButton();
        btn_salvar = new javax.swing.JButton();
        AdicionarPet = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_nome2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lb_nome2.setForeground(new java.awt.Color(1, 141, 185));
        lb_nome2.setText("Nome:");
        getContentPane().add(lb_nome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        lb_especie.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lb_especie.setForeground(new java.awt.Color(1, 141, 185));
        lb_especie.setText("Raça:");
        getContentPane().add(lb_especie, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        lb_idade.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lb_idade.setForeground(new java.awt.Color(1, 141, 185));
        lb_idade.setText("Idade:");
        getContentPane().add(lb_idade, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, -1, -1));

        tf_nome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(1, 141, 185), 2, true));
        tf_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nomeActionPerformed(evt);
            }
        });
        getContentPane().add(tf_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 320, 40));

        tf_raca.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(1, 141, 185), 2, true));
        tf_raca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_racaActionPerformed(evt);
            }
        });
        getContentPane().add(tf_raca, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 160, 40));

        tf_idade.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(1, 141, 185), 2, true));
        tf_idade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_idadeActionPerformed(evt);
            }
        });
        getContentPane().add(tf_idade, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 80, 40));

        btn_voltar.setContentAreaFilled(false);
        btn_voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_voltar.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                btn_voltarCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 120, 40));

        btn_salvar.setContentAreaFilled(false);
        btn_salvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 120, 40));

        AdicionarPet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/AdicionarPet.png"))); // NOI18N
        getContentPane().add(AdicionarPet, new org.netbeans.lib.awtextra.AbsoluteConstraints(-11, 0, 750, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_idadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_idadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_idadeActionPerformed

    private void tf_racaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_racaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_racaActionPerformed

    private void btn_voltarCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_btn_voltarCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_voltarCaretPositionChanged

    private void tf_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nomeActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
         // Ação após clicar no Botão Voltar
        this.controller.voltarAoMenu();
    }//GEN-LAST:event_btn_voltarActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        this.controller.cadastrarPet();
    }//GEN-LAST:event_btn_salvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionarPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionarPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionarPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionarPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdicionarPet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdicionarPet;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JLabel lb_especie;
    private javax.swing.JLabel lb_idade;
    private javax.swing.JLabel lb_nome2;
    private javax.swing.JTextField tf_idade;
    private javax.swing.JTextField tf_nome;
    private javax.swing.JTextField tf_raca;
    // End of variables declaration//GEN-END:variables

    public JTextField getTf_nome() {
        return tf_nome;
    }

    public void setTf_nome(JTextField tf_nome) {
        this.tf_nome = tf_nome;
    }

    public JTextField getTf_raca() {
        return tf_raca;
    }

    public void setTf_raca(JTextField tf_raca) {
        this.tf_raca = tf_raca;
    }

    public JTextField getTf_idade() {
        return tf_idade;
    }

    public void setTf_idade(JTextField tf_idade) {
        this.tf_idade = tf_idade;
    }
    
}
