/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Usuário
 */
public class CadastroServiço extends javax.swing.JFrame {

    /**
     * Creates new form CadastroServiço
     */
    public CadastroServiço() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_excluir_servico = new javax.swing.JButton();
        btn_cadastrar_servico = new javax.swing.JButton();
        btn_voltar_servico = new javax.swing.JButton();
        tf_id = new javax.swing.JTextField();
        tf_funcionario = new javax.swing.JTextField();
        tf_valor = new javax.swing.JTextField();
        tf_nome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_excluir_servico.setContentAreaFilled(false);
        btn_excluir_servico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluir_servicoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_excluir_servico, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 110, 40));

        btn_cadastrar_servico.setContentAreaFilled(false);
        btn_cadastrar_servico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrar_servicoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cadastrar_servico, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 110, 40));

        btn_voltar_servico.setContentAreaFilled(false);
        btn_voltar_servico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_voltar_servico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltar_servicoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_voltar_servico, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 40, 50));

        tf_id.setBorder(null);
        tf_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_idActionPerformed(evt);
            }
        });
        getContentPane().add(tf_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 190, 30));

        tf_funcionario.setBorder(null);
        tf_funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_funcionarioActionPerformed(evt);
            }
        });
        getContentPane().add(tf_funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 190, 30));

        tf_valor.setBorder(null);
        tf_valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_valorActionPerformed(evt);
            }
        });
        getContentPane().add(tf_valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 160, 30));

        tf_nome.setBorder(null);
        tf_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nomeActionPerformed(evt);
            }
        });
        getContentPane().add(tf_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 190, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Id", "Funcionário", "Valor"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 690, 140));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/CadastroServiço.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 760, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastrar_servicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrar_servicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cadastrar_servicoActionPerformed

    private void tf_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_idActionPerformed

    private void tf_funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_funcionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_funcionarioActionPerformed

    private void tf_valorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_valorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_valorActionPerformed

    private void tf_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nomeActionPerformed

    private void btn_excluir_servicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluir_servicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_excluir_servicoActionPerformed

    private void btn_voltar_servicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltar_servicoActionPerformed
         // Ação após clicar no Botão Voltar
        SubMenuCadastro novoFrame = new SubMenuCadastro();
        novoFrame.setVisible(true);
    }//GEN-LAST:event_btn_voltar_servicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroServiço.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroServiço.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroServiço.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroServiço.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroServiço().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrar_servico;
    private javax.swing.JButton btn_excluir_servico;
    private javax.swing.JButton btn_voltar_servico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tf_funcionario;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_nome;
    private javax.swing.JTextField tf_valor;
    // End of variables declaration//GEN-END:variables
}
