package View;

import Controller.ProdutoController;
import javax.swing.JTable;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Usuário
 */
public class CadastroProduto extends javax.swing.JFrame {
    
    private final ProdutoController controller;
    /**
     * Creates new form CadastroProduto
     */
    public CadastroProduto() {
        initComponents();
        controller = new ProdutoController(this);
        
        // Adicione um listener para o evento de visibilidade da janela
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowOpened(java.awt.event.WindowEvent evt) {
                controller.atualizaTabela();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_voltar = new javax.swing.JButton();
        btn_cadastrar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        tf_nome = new javax.swing.JTextField();
        tf_id = new javax.swing.JTextField();
        tf_fornecedor = new javax.swing.JTextField();
        tf_valor = new javax.swing.JTextField();
        tf_validade = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProdutos = new javax.swing.JTable();
        Fundo_CadastroProduto = new javax.swing.JLabel();

        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_voltar.setContentAreaFilled(false);
        btn_voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 40, 40));

        btn_cadastrar.setContentAreaFilled(false);
        btn_cadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 90, 40));

        btn_excluir.setContentAreaFilled(false);
        btn_excluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 90, 40));

        tf_nome.setBorder(null);
        getContentPane().add(tf_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 150, 30));

        tf_id.setBorder(null);
        getContentPane().add(tf_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 150, 30));

        tf_fornecedor.setBorder(null);
        getContentPane().add(tf_fornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 150, 30));

        tf_valor.setBorder(null);
        getContentPane().add(tf_valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 100, 30));

        tf_validade.setBorder(null);
        getContentPane().add(tf_validade, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 286, 130, 30));

        tableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "Código", "Fornecedor", "Valor", "Validade"
            }
        ));
        jScrollPane1.setViewportView(tableProdutos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 660, 140));

        Fundo_CadastroProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/CadastroProduto.png"))); // NOI18N
        getContentPane().add(Fundo_CadastroProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 740, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        this.controller.cadastrarProduto();
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        // Ação após clicar no Botão Voltar
        SubMenuCadastro novoFrame = new SubMenuCadastro();
        novoFrame.setVisible(true);
    }//GEN-LAST:event_btn_voltarActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        this.controller.excluirProduto();
    }//GEN-LAST:event_btn_excluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fundo_CadastroProduto;
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableProdutos;
    private javax.swing.JTextField tf_fornecedor;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_nome;
    private javax.swing.JTextField tf_validade;
    private javax.swing.JTextField tf_valor;
    // End of variables declaration//GEN-END:variables

    private void iniciar(){
        this.controller.atualizaTabela();
    }

    public JTable getTableProdutos() {
        return tableProdutos;
    }

    public void setTableProdutos(JTable tableProdutos) {
        this.tableProdutos = tableProdutos;
    }

    public JTextField getTf_fornecedor() {
        return tf_fornecedor;
    }

    public void setTf_fornecedor(JTextField tf_fornecedor) {
        this.tf_fornecedor = tf_fornecedor;
    }

    public JTextField getTf_id() {
        return tf_id;
    }

    public void setTf_id(JTextField tf_id) {
        this.tf_id = tf_id;
    }

    public JTextField getTf_nome() {
        return tf_nome;
    }

    public void setTf_nome(JTextField tf_nome) {
        this.tf_nome = tf_nome;
    }

    public JTextField getTf_validade() {
        return tf_validade;
    }

    public void setTf_validade(JTextField tf_validade) {
        this.tf_validade = tf_validade;
    }

    public JTextField getTf_valor() {
        return tf_valor;
    }

    public void setTf_valor(JTextField tf_valor) {
        this.tf_valor = tf_valor;
    }
    
    
    
    
}
