/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.CadastroController;
import javax.swing.JTextField;

/**
 *
 * @author Usuário
 */
public class Cadastro extends javax.swing.JFrame {
    private final CadastroController controller;
    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
        this.controller = new CadastroController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        lb_nome = new javax.swing.JLabel();
        tf_nome = new javax.swing.JTextField();
        lb_email = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        lb_senha = new javax.swing.JLabel();
        tf_senha = new javax.swing.JTextField();
        lb_repetirSenha = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        btn_cadastrar = new javax.swing.JButton();
        Cadastre = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_nome.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lb_nome.setForeground(new java.awt.Color(1, 141, 185));
        lb_nome.setText("Nome:");
        getContentPane().add(lb_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        tf_nome.setBackground(new java.awt.Color(255, 255, 255));
        tf_nome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(1, 141, 185), 2, true));
        tf_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nomeActionPerformed(evt);
            }
        });
        getContentPane().add(tf_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 330, 40));

        lb_email.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lb_email.setForeground(new java.awt.Color(1, 141, 185));
        lb_email.setText("E-mail:");
        getContentPane().add(lb_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(1, 141, 185), 2, true));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 330, 40));

        lb_senha.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lb_senha.setForeground(new java.awt.Color(1, 141, 185));
        lb_senha.setText("Senha:");
        getContentPane().add(lb_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 60, -1));

        tf_senha.setBackground(new java.awt.Color(255, 255, 255));
        tf_senha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(1, 141, 185), 2, true));
        tf_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_senhaActionPerformed(evt);
            }
        });
        getContentPane().add(tf_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 330, 40));

        lb_repetirSenha.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lb_repetirSenha.setForeground(new java.awt.Color(1, 141, 185));
        lb_repetirSenha.setText("Repetir Senha:");
        getContentPane().add(lb_repetirSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, -1, -1));

        jTextField7.setBackground(new java.awt.Color(255, 255, 255));
        jTextField7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(1, 141, 185), 2, true));
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 260, 40));

        btn_cadastrar.setContentAreaFilled(false);
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 140, 50));

        Cadastre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Cadastro.png"))); // NOI18N
        getContentPane().add(Cadastre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void tf_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_senhaActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void tf_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nomeActionPerformed

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        this.controller.cadastrarNoSistema();
        //this.controller.navegarParaLogin();
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cadastre;
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel lb_email;
    private javax.swing.JLabel lb_nome;
    private javax.swing.JLabel lb_repetirSenha;
    private javax.swing.JLabel lb_senha;
    private javax.swing.JTextField tf_nome;
    private javax.swing.JTextField tf_senha;
    // End of variables declaration//GEN-END:variables

    public JTextField getTf_nome() {
        return tf_nome;
    }

    public void setTf_nome(JTextField tf_nome) {
        this.tf_nome = tf_nome;
    }

    public JTextField getTf_senha() {
        return tf_senha;
    }

    public void setTf_senha(JTextField tf_senha) {
        this.tf_senha = tf_senha;
    }

    

}


