/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Usuário
 */
public class SubMenuCadastro extends javax.swing.JFrame {

    /**
     * Creates new form SubMenuCadastro
     */
    public SubMenuCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_voltar = new javax.swing.JButton();
        btn_Pet = new javax.swing.JButton();
        btn_Cliente = new javax.swing.JButton();
        btn_Serviço = new javax.swing.JButton();
        btn_Produto = new javax.swing.JButton();
        SubMenuCadastro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_voltar.setContentAreaFilled(false);
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 50, 50));

        btn_Pet.setContentAreaFilled(false);
        btn_Pet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PetActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Pet, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 150, 200, 140));

        btn_Cliente.setContentAreaFilled(false);
        btn_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 150, 210, 130));

        btn_Serviço.setContentAreaFilled(false);
        btn_Serviço.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ServiçoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Serviço, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 210, 130));

        btn_Produto.setContentAreaFilled(false);
        btn_Produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Produto, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 210, 130));

        SubMenuCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/SubMenuCadastro.png"))); // NOI18N
        getContentPane().add(SubMenuCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 556));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        // Ação após clicar no Botão Voltar
        MenuPrincipal novoFrame = new MenuPrincipal();
        novoFrame.setVisible(true);
    }//GEN-LAST:event_btn_voltarActionPerformed

    private void btn_PetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PetActionPerformed
        // Ação após clicar no Botão Cadastrar Pet
        AdicionarPet novoFrame = new AdicionarPet();
        novoFrame.setVisible(true);
    }//GEN-LAST:event_btn_PetActionPerformed

    private void btn_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClienteActionPerformed
        // Ação após clicar no Botão Cadastrar Cliente
        CadastroCliente novoFrame = new CadastroCliente();
        novoFrame.setVisible(true);
    }//GEN-LAST:event_btn_ClienteActionPerformed

    private void btn_ServiçoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ServiçoActionPerformed
        // Ação após clicar no Botão Cadastrar Serviço
        CadastroServiço novoFrame = new CadastroServiço();
        novoFrame.setVisible(true);
    }//GEN-LAST:event_btn_ServiçoActionPerformed

    private void btn_ProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ProdutoActionPerformed
        // Ação após clicar no Botão Cadastrar Produto
        CadastroProduto novoFrame = new CadastroProduto();
        novoFrame.setVisible(true);
    }//GEN-LAST:event_btn_ProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubMenuCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubMenuCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubMenuCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubMenuCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubMenuCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SubMenuCadastro;
    private javax.swing.JButton btn_Cliente;
    private javax.swing.JButton btn_Pet;
    private javax.swing.JButton btn_Produto;
    private javax.swing.JButton btn_Serviço;
    private javax.swing.JButton btn_voltar;
    // End of variables declaration//GEN-END:variables
}
